import { BellRing, CheckCircle2, Download, Eye, FileClock, Filter, Search, ShieldAlert, ShieldCheck, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import AlertsTable from "../../components/AlertsTable";
import ConfirmDialog from "../../components/common/ConfirmDialog";
import EmptyState from "../../components/common/EmptyState";
import ErrorBanner from "../../components/common/ErrorBanner";
import MetricCard from "../../components/common/MetricCard";
import PageHeader from "../../components/common/PageHeader";
import StatusBadge from "../../components/common/StatusBadge";
import { useToast } from "../../contexts/ToastContext";
import useAuth from "../../hooks/useAuth";
import { clearDashboardData, getAlerts, getLivePredictions } from "../../services/api";
import { downloadCsv, formatConfidence, formatDateTime } from "../../utils/formatters";

export default function AlertsLogsPage() {
  const { hasPermission } = useAuth(); const { push } = useToast(); const [tab, setTab] = useState("alerts"); const [alerts, setAlerts] = useState([]); const [logs, setLogs] = useState([]); const [reviewed, setReviewed] = useState(() => JSON.parse(localStorage.getItem("netshield.reviewed-alerts") || "[]")); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [severity, setSeverity] = useState("ALL"); const [prediction, setPrediction] = useState("ALL"); const [selected, setSelected] = useState(null); const [confirmClear, setConfirmClear] = useState(false);
  const load = useCallback(async () => { setLoading(true); const results = await Promise.allSettled([getAlerts(200), getLivePredictions(200)]); if (results[0].status === "fulfilled") setAlerts(results[0].value.data || []); if (results[1].status === "fulfilled") setLogs(results[1].value.data || []); setError(results.every((result) => result.status === "rejected") ? "Alerts and prediction logs are unavailable while FastAPI is offline." : ""); setLoading(false); }, []);
  useEffect(() => { load(); }, [load]);
  const markReviewed = (id) => { const next = [...new Set([...reviewed, id])]; setReviewed(next); localStorage.setItem("netshield.reviewed-alerts", JSON.stringify(next)); push("Alert marked as reviewed on this device."); };
  const filteredLogs = useMemo(() => logs.filter((row) => prediction === "ALL" || row.prediction === prediction).filter((row) => [row.src_ip, row.dst_ip, row.protocol, row.prediction].some((value) => String(value || "").toLowerCase().includes(query.toLowerCase()))), [logs, prediction, query]);
  const filteredAlerts = useMemo(() => alerts.filter((row) => severity === "ALL" || row.severity === severity).filter((row) => [row.source, row.destination, row.alert_type].some((value) => String(value || "").toLowerCase().includes(query.toLowerCase()))), [alerts, severity, query]);
  const exportRows = () => { const rows = tab === "alerts" ? filteredAlerts : filteredLogs; if (downloadCsv(`netshield-${tab}-${new Date().toISOString().slice(0, 10)}.csv`, rows)) push(`${tab === "alerts" ? "Alerts" : "Logs"} exported.`); else push("There is no data to export.", "error"); };
  const severities = (value) => alerts.filter((row) => row.severity === value).length;
  return <div className="page-stack"><PageHeader eyebrow="Security operations" title="Alerts & prediction logs" description="Investigate attack signals, review evidence, filter activity, and export operational records." actions={<div className="page-actions"><button className="button button-ghost" onClick={exportRows}><Download size={16}/>Export {tab}</button>{hasPermission("alerts:clear") && <button className="button button-danger-soft" onClick={() => setConfirmClear(true)}><Trash2 size={16}/>Clear stored data</button>}</div>} />{error && <ErrorBanner message={error} onRetry={load}/>}<section className="metrics-grid"><MetricCard icon={ShieldAlert} label="High alerts" value={severities("HIGH")} detail="Highest-priority detections" tone="danger"/><MetricCard icon={BellRing} label="Medium alerts" value={severities("MEDIUM")} detail="Needs analyst attention" tone="warning"/><MetricCard icon={BellRing} label="Low alerts" value={severities("LOW")} detail="Lower-risk detections" tone="info"/><MetricCard icon={ShieldCheck} label="Reviewed alerts" value={alerts.filter((row) => reviewed.includes(row.id)).length} detail="Reviewed on this device" tone="success"/><MetricCard icon={FileClock} label="Open alerts" value={alerts.filter((row) => !reviewed.includes(row.id)).length} detail="Awaiting review" tone="primary"/></section>
    <section className="soc-panel"><div className="tab-bar" role="tablist"><button className={tab === "alerts" ? "active" : ""} onClick={() => setTab("alerts")}><BellRing size={16}/>Alerts <span>{alerts.length}</span></button><button className={tab === "logs" ? "active" : ""} onClick={() => setTab("logs")}><FileClock size={16}/>Prediction logs <span>{logs.length}</span></button></div><div className="soc-filters"><label className="search-field"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search IP, protocol, or type" /></label><span><Filter size={15}/>Filters</span>{tab === "alerts" ? <select value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="ALL">All severities</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select> : <select value={prediction} onChange={(event) => setPrediction(event.target.value)}><option value="ALL">All predictions</option><option>BENIGN</option><option>DDoS</option></select>}</div>{tab === "alerts" ? <AlertsTable alerts={filteredAlerts} loading={loading} reviewed={reviewed} onReview={markReviewed} onView={setSelected}/> : loading ? <div className="table-skeleton"><i/><i/><i/><i/></div> : filteredLogs.length ? <div className="table-scroll"><table><thead><tr><th>ID</th><th>Source IP</th><th>Destination IP</th><th>Protocol</th><th>Packets</th><th>Prediction</th><th>Confidence</th><th>Mode</th><th>Timestamp</th><th>Action</th></tr></thead><tbody>{filteredLogs.map((row) => <tr key={row.id}><td className="mono muted">#{row.id}</td><td className="mono">{row.src_ip}</td><td className="mono">{row.dst_ip}</td><td>{row.protocol}</td><td>{row.packets}</td><td><StatusBadge tone={row.prediction === "DDoS" ? "danger" : "success"} dot>{row.prediction}</StatusBadge></td><td>{formatConfidence(row.confidence)}</td><td><StatusBadge tone="neutral">Stored</StatusBadge></td><td className="muted">{formatDateTime(row.created_at)}</td><td><button className="icon-button" onClick={() => setSelected({ ...row, kind: "log" })} aria-label="View log"><Eye size={16}/></button></td></tr>)}</tbody></table></div> : <EmptyState title="No prediction logs found" message="Change the filter or generate traffic from the capture and replay controls."/>}</section>
    <div className="source-note"><CheckCircle2 size={16}/><div><strong>Real stored activity</strong><p>Alerts and prediction logs come directly from the existing SQLite-backed FastAPI endpoints. Review state is currently local to this browser because the backend has no acknowledgement endpoint.</p></div></div>
    {selected && <div className="modal-backdrop" onMouseDown={() => setSelected(null)}><section className="drawer alert-drawer" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><button className="dialog-close icon-button" onClick={() => setSelected(null)} aria-label="Close"><X size={19}/></button><span className="eyebrow">{selected.kind === "log" ? "Prediction log" : "Security alert"}</span><h2>{selected.alert_type || `${selected.prediction} traffic event`}</h2><div className="alert-identity"><StatusBadge tone={(selected.severity === "HIGH" || selected.prediction === "DDoS") ? "danger" : "success"} dot>{selected.severity || selected.prediction}</StatusBadge><span>{formatDateTime(selected.created_at || selected.timestamp)}</span></div><div className="detail-metrics"><div><span>Source</span><strong className="mono">{selected.source || selected.src_ip}</strong></div><div><span>Destination</span><strong className="mono">{selected.destination || selected.dst_ip}</strong></div><div><span>Confidence</span><strong>{formatConfidence(selected.confidence)}</strong></div><div><span>Protocol</span><strong>{selected.protocol || "TCP"}</strong></div><div><span>Packets</span><strong>{selected.total_packets || selected.packets || "—"}</strong></div><div><span>Status</span><strong>{reviewed.includes(selected.id) ? "Reviewed" : "Open"}</strong></div></div><div className="detail-block"><h3>Prediction reason</h3><p>Not persisted by the current backend. Manual predictions provide a generated reason at inference time.</p></div>{!reviewed.includes(selected.id) && selected.kind !== "log" && <button className="button button-primary" onClick={() => { markReviewed(selected.id); setSelected(null); }}><ShieldCheck size={16}/>Mark reviewed</button>}</section></div>}
    <ConfirmDialog open={confirmClear} title="Clear alerts and prediction logs?" message="The current backend clears both SQLite tables together. This operation cannot be undone." confirmLabel="Clear all stored data" onCancel={() => setConfirmClear(false)} onConfirm={async () => { setConfirmClear(false); try { await clearDashboardData(); push("Alerts and prediction logs cleared."); load(); } catch { push("The backend could not clear stored data.", "error"); } }}/>
  </div>;
}
