import { Activity, BellRing, Download, Network, Play, Radio, RotateCcw, ShieldAlert, ShieldCheck, Square, Trash2, Waves } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import AlertsTable from "../../components/AlertsTable";
import TrafficTable from "../../components/TrafficTable";
import ConfirmDialog from "../../components/common/ConfirmDialog";
import ErrorBanner from "../../components/common/ErrorBanner";
import MetricCard from "../../components/common/MetricCard";
import PageHeader from "../../components/common/PageHeader";
import StatusBadge from "../../components/common/StatusBadge";
import { useToast } from "../../contexts/ToastContext";
import useAuth from "../../hooks/useAuth";
import { clearDashboardData, getAlerts, getCaptureStatus, getLivePredictions, getStats, replayBenign, replayDdos, startCapture, stopCapture } from "../../services/api";
import { downloadCsv, formatConfidence, formatNumber } from "../../utils/formatters";

const emptyStats = { total_predictions: 0, benign_count: 0, ddos_count: 0, alert_count: 0, average_confidence: 0 };

export default function DashboardPage() {
  const { user, hasPermission } = useAuth(); const { push } = useToast();
  const [stats, setStats] = useState(emptyStats); const [predictions, setPredictions] = useState([]); const [alerts, setAlerts] = useState([]); const [capture, setCapture] = useState({});
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(""); const [confirmClear, setConfirmClear] = useState(false); const [lastSync, setLastSync] = useState(null);
  const load = useCallback(async (silent = false) => { if (!silent) setLoading(true); const results = await Promise.allSettled([getStats(), getLivePredictions(100), getAlerts(100), getCaptureStatus()]); const failed = results.filter((result) => result.status === "rejected"); if (failed.length === results.length) setError("NetShield backend is offline. Start FastAPI to restore live security data."); else { setError(failed.length ? "Some security services did not respond. Available data is shown below." : ""); if (results[0].status === "fulfilled") setStats(results[0].value.data || emptyStats); if (results[1].status === "fulfilled") setPredictions(results[1].value.data || []); if (results[2].status === "fulfilled") setAlerts(results[2].value.data || []); if (results[3].status === "fulfilled") setCapture(results[3].value.data || {}); setLastSync(new Date()); } setLoading(false); }, []);
  useEffect(() => { load(); const timer = setInterval(() => load(true), 5000); return () => clearInterval(timer); }, [load]);
  const action = async (key, fn, success) => { setBusy(key); try { const result = await fn(); push(typeof success === "function" ? success(result) : success); await load(true); } catch (err) { push(err.response?.data?.detail || "The backend could not complete this action.", "error"); } finally { setBusy(""); } };
  const distribution = [{ name: "BENIGN", value: stats.benign_count, color: "#18a979" }, { name: "DDoS", value: stats.ddos_count, color: "#df4c5b" }];
  const timeline = useMemo(() => [...predictions].reverse().slice(-18).map((row, index) => ({ index: index + 1, confidence: Math.round((row.confidence || 0) * 100), packets: row.packets, benign: row.prediction === "BENIGN" ? 1 : 0, ddos: row.prediction === "DDoS" ? 1 : 0 })), [predictions]);
  const severity = useMemo(() => ["HIGH", "MEDIUM", "LOW"].map((name) => ({ name, value: alerts.filter((row) => row.severity === name).length })), [alerts]);
  const captureAvailable = capture.capture_enabled === true;
  const demoMode = capture.demo_mode !== false;
  const exportReport = () => { const rows = predictions.map((row) => ({ ...row, confidence_percent: formatConfidence(row.confidence) })); if (downloadCsv(`netshield-report-${new Date().toISOString().slice(0, 10)}.csv`, rows)) push("Prediction report exported."); else push("There is no prediction data to export.", "error"); };
  return <div className="page-stack"><PageHeader eyebrow="Command center" title={`Welcome back, ${user?.name}.`} description="Monitor your detection posture, capture activity, and recent threat signals." aside={<div className="health-summary"><StatusBadge tone={error ? "warning" : "success"} dot>{error ? "Degraded" : "Systems operational"}</StatusBadge><span>Last sync {lastSync ? lastSync.toLocaleTimeString() : "—"}</span></div>} />
    {error && <ErrorBanner message={error} onRetry={() => load()} />}
    <section className="quick-actions-card"><div><span className={`capture-pulse ${capture.is_running ? "active" : ""}`}><Radio size={19} /></span><div><strong>Detection controls</strong><p>{!captureAvailable ? "Cloud demo: use the replay controls below" : capture.is_running ? `Live since ${capture.started_at}` : "Capture is currently stopped"}</p></div></div><div className="quick-actions"><button className="button button-success" title={!captureAvailable ? "Live packet capture is disabled in the cloud demo" : undefined} disabled={busy || capture.is_running || !captureAvailable} onClick={() => action("start", startCapture, "Live capture started.")}><Play size={16} />Start capture</button><button className="button button-danger-soft" disabled={busy || !capture.is_running || !captureAvailable} onClick={() => action("stop", stopCapture, "Live capture stopped.")}><Square size={15} />Stop</button><button className="button button-ghost" disabled={busy} onClick={() => action("benign", () => replayBenign(10), (result) => `${result.saved_predictions} BENIGN samples replayed.`)}><RotateCcw size={16} />Replay BENIGN</button><button className="button button-warning" disabled={busy} onClick={() => action("ddos", () => replayDdos(10), (result) => `${result.saved_predictions} DDoS samples replayed.`)}><ShieldAlert size={16} />Replay DDoS</button><button className="button button-ghost" onClick={exportReport}><Download size={16} />Export</button>{hasPermission("alerts:clear") && !demoMode && <button className="button button-danger-soft" onClick={() => setConfirmClear(true)}><Trash2 size={16} />Clear all</button>}</div></section>
    <section className="metrics-grid metrics-grid-seven"><MetricCard icon={Activity} label="Total predictions" value={formatNumber(stats.total_predictions)} detail="All analyzed flow snapshots" tone="primary" /><MetricCard icon={ShieldCheck} label="BENIGN traffic" value={formatNumber(stats.benign_count)} detail="Normal network activity" tone="success" /><MetricCard icon={ShieldAlert} label="DDoS traffic" value={formatNumber(stats.ddos_count)} detail="Detected attack activity" tone="danger" /><MetricCard icon={BellRing} label="Active alerts" value={formatNumber(stats.alert_count)} detail="Open security warnings" tone="warning" /><MetricCard icon={Waves} label="Avg. confidence" value={formatConfidence(stats.average_confidence)} detail="Across stored predictions" tone="info" /><MetricCard icon={Radio} label="Packets processed" value={formatNumber(capture.packet_count)} detail="Current capture session" tone="neutral" /><MetricCard icon={Network} label="Active flows" value={formatNumber(capture.total_flows)} detail="In-memory flow builder" tone="neutral" /></section>
    <section className="chart-grid"><article className="chart-card"><div className="panel-heading"><div><h2>Traffic distribution</h2><p>BENIGN versus DDoS classifications</p></div></div><div className="donut-wrap"><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={distribution} dataKey="value" innerRadius={62} outerRadius={86} paddingAngle={4}>{distribution.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="donut-center"><strong>{formatNumber(stats.total_predictions)}</strong><span>Total</span></div></div><div className="chart-legend">{distribution.map((entry) => <span key={entry.name}><i style={{ background: entry.color }} />{entry.name}<strong>{formatNumber(entry.value)}</strong></span>)}</div></article><article className="chart-card chart-card-wide"><div className="panel-heading"><div><h2>Detection activity</h2><p>Confidence and packet volume across recent predictions</p></div></div><ResponsiveContainer width="100%" height={260}><AreaChart data={timeline}><defs><linearGradient id="confidenceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#7667f5" stopOpacity={0.3}/><stop offset="95%" stopColor="#7667f5" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#e9e8ef" vertical={false} /><XAxis dataKey="index" tick={{ fill: "#838194", fontSize: 11 }} /><YAxis domain={[0, 100]} tick={{ fill: "#838194", fontSize: 11 }} /><Tooltip /><Area type="monotone" dataKey="confidence" stroke="#7667f5" strokeWidth={2} fill="url(#confidenceFill)" /></AreaChart></ResponsiveContainer></article><article className="chart-card"><div className="panel-heading"><div><h2>Alert severity</h2><p>Current alert distribution</p></div></div><ResponsiveContainer width="100%" height={220}><BarChart data={severity}><CartesianGrid stroke="#e9e8ef" vertical={false} /><XAxis dataKey="name" tick={{ fill: "#838194", fontSize: 11 }} /><YAxis allowDecimals={false} tick={{ fill: "#838194", fontSize: 11 }} /><Tooltip /><Bar dataKey="value" fill="#eaa42b" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></article></section>
    <TrafficTable predictions={predictions} loading={loading} /><AlertsTable alerts={alerts} loading={loading} limit={6} />
    <ConfirmDialog open={confirmClear} title="Clear all detection data?" message="This permanently removes every stored prediction and alert from the NetShield database. Model files and datasets are not affected." confirmLabel="Clear all data" onCancel={() => setConfirmClear(false)} onConfirm={() => { setConfirmClear(false); action("clear", clearDashboardData, "All stored predictions and alerts were cleared."); }} />
  </div>;
}
