import { ArrowRight, BarChart3, CheckCircle2, Database, FileText, Filter, FlaskConical, Rows3, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import MetricCard from "../../components/common/MetricCard";
import PageHeader from "../../components/common/PageHeader";
import StatusBadge from "../../components/common/StatusBadge";
import { datasetStats, sampleFlows, selectedFeatureDetails } from "../../data/projectData";
import { formatNumber } from "../../utils/formatters";

const processing = ["Two source files loaded", "Labels filtered to BENIGN and DDoS", "Duplicates reviewed", "Missing values handled", "Infinity values replaced", "Leakage columns excluded", "Labels encoded", "80/20 train-test split", "StandardScaler applied"];

export default function DatasetOverviewPage() {
  const navigate = useNavigate(); const [label, setLabel] = useState("ALL"); const [query, setQuery] = useState("");
  const rows = useMemo(() => sampleFlows.filter((row) => label === "ALL" || row.label === label).filter((row) => JSON.stringify(row.features).toLowerCase().includes(query.toLowerCase())), [label, query]);
  const distribution = [{ name: "BENIGN", value: datasetStats.benign, color: "#18a979" }, { name: "DDoS", value: datasetStats.ddos, color: "#df4c5b" }];
  const selectedRates = sampleFlows.map((row, index) => ({ sample: `S${index + 1}`, type: row.label, bytes: Math.min(row.features["Flow Bytes/s"], 700000), packets: Math.min(row.features["Flow Packets/s"], 500) }));
  return <div className="page-stack"><PageHeader eyebrow="Training intelligence" title="CIC-IDS2017 dataset" description="Inspect source files, class balance, processing lineage, and the exact deployment features." aside={<StatusBadge tone="success"><CheckCircle2 size={13} />Local dataset available</StatusBadge>} />
    <section className="metrics-grid"><MetricCard icon={Database} label="Total records" value={formatNumber(datasetStats.total)} detail="Across two source CSV files" tone="primary" /><MetricCard icon={Rows3} label="BENIGN records" value={formatNumber(datasetStats.benign)} detail="Monday plus Friday traffic" tone="success" /><MetricCard icon={BarChart3} label="DDoS records" value={formatNumber(datasetStats.ddos)} detail="Friday afternoon DDoS traffic" tone="danger" /><MetricCard icon={FileText} label="Raw columns" value={datasetStats.rawColumns} detail="Including the label column" tone="neutral" /><MetricCard icon={Filter} label="Selected features" value={datasetStats.selectedFeatures} detail="Deployment input contract" tone="info" /><MetricCard icon={FlaskConical} label="Train / test split" value={`${datasetStats.trainSplit} / ${datasetStats.testSplit}`} detail="Final evaluation workflow" tone="warning" /></section>
    <section className="dataset-chart-grid"><article className="chart-card"><div className="panel-heading"><div><h2>Class distribution</h2><p>All records across the bundled source files</p></div></div><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={distribution} dataKey="value" innerRadius={58} outerRadius={86} paddingAngle={4}>{distribution.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip formatter={(value) => formatNumber(value)} /></PieChart></ResponsiveContainer><div className="chart-legend">{distribution.map((item) => <span key={item.name}><i style={{ background: item.color }} />{item.name}<strong>{formatNumber(item.value)}</strong></span>)}</div></article><article className="chart-card chart-card-wide"><div className="panel-heading"><div><h2>Bundled sample traffic rates</h2><p>Clipped preview from real sample.csv rows</p></div><StatusBadge tone="info">Real samples</StatusBadge></div><ResponsiveContainer width="100%" height={280}><BarChart data={selectedRates}><CartesianGrid stroke="#e9e8ef" vertical={false}/><XAxis dataKey="sample"/><YAxis/><Tooltip/><Bar dataKey="packets" name="Packets/s (clipped)" fill="#7667f5" radius={[5, 5, 0, 0]} /><Bar dataKey="bytes" name="Bytes/s (clipped)" fill="#3182ce" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></article></section>
    <section className="data-panel"><div className="panel-heading"><div><h2>Dataset processing lineage</h2><p>Steps represented in the final training notebook</p></div></div><div className="processing-grid">{processing.map((step, index) => <div key={step}><span><CheckCircle2 size={16} /></span><div><small>STEP {String(index + 1).padStart(2, "0")}</small><strong>{step}</strong></div></div>)}</div></section>
    <section className="data-panel"><div className="panel-heading"><div><h2>Selected deployment features</h2><p>The fixed 12-feature contract used by capture and manual prediction</p></div><StatusBadge tone="primary">selected_features.pkl</StatusBadge></div><div className="table-scroll"><table><thead><tr><th>Feature</th><th>Meaning</th><th>Unit</th><th>Category</th><th>Example</th></tr></thead><tbody>{selectedFeatureDetails.map((feature) => <tr key={feature.name}><td><strong>{feature.name}</strong></td><td>{feature.meaning}</td><td>{feature.unit}</td><td><StatusBadge tone="neutral">{feature.category}</StatusBadge></td><td className="mono">{feature.example}</td></tr>)}</tbody></table></div></section>
    <section className="data-panel"><div className="panel-heading"><div><h2>Dataset samples</h2><p>Real rows from the bundled sample.csv export</p></div><div className="table-tools"><label className="search-field"><Search size={16}/><input placeholder="Search sample values" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select value={label} onChange={(event) => setLabel(event.target.value)}><option value="ALL">All labels</option><option value="BENIGN">BENIGN</option><option value="DDoS">DDoS</option></select></div></div><div className="table-scroll"><table><thead><tr><th>Expected label</th><th>Flow duration</th><th>Fwd packets</th><th>Bwd packets</th><th>Flow bytes/s</th><th>Packet mean</th><th>Source</th><th>Action</th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.label}-${index}`}><td><StatusBadge tone={row.label === "DDoS" ? "danger" : "success"} dot>{row.label}</StatusBadge></td><td>{formatNumber(row.features["Flow Duration"])}</td><td>{row.features["Total Fwd Packets"]}</td><td>{row.features["Total Backward Packets"]}</td><td>{formatNumber(row.features["Flow Bytes/s"], 2)}</td><td>{formatNumber(row.features["Packet Length Mean"], 2)}</td><td className="source-cell">{row.source}</td><td><button className="text-button" onClick={() => navigate("/manual-prediction", { state: { sample: row } })}>Use in prediction <ArrowRight size={14}/></button></td></tr>)}</tbody></table></div></section>
    <div className="source-note"><Database size={16}/><div><strong>Verified local dataset snapshot</strong><p>Counts were computed directly from the two bundled CIC-IDS2017 CSV files: 529,918 Monday BENIGN rows plus 97,718 Friday BENIGN and 128,027 Friday DDoS rows.</p></div></div>
  </div>;
}
