import { Activity, Ban, Clock3, Network, Pause, Play, Radio, RotateCcw, ShieldAlert, ShieldCheck, Square, Trash2, Waves, Zap } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import TrafficTable from "../../components/TrafficTable";
import ConfirmDialog from "../../components/common/ConfirmDialog";
import ErrorBanner from "../../components/common/ErrorBanner";
import MetricCard from "../../components/common/MetricCard";
import PageHeader from "../../components/common/PageHeader";
import StatusBadge from "../../components/common/StatusBadge";
import { useToast } from "../../contexts/ToastContext";
import useAuth from "../../hooks/useAuth";
import { clearDashboardData, getCaptureStatus, getLivePredictions, getStats, replayBenign, replayDdos, startCapture, stopCapture } from "../../services/api";
import { formatConfidence, formatNumber } from "../../utils/formatters";

export default function LiveCapturePage() {
  const { hasPermission } = useAuth(); const { push } = useToast(); const [networkInterface, setNetworkInterface] = useState(""); const [status, setStatus] = useState({}); const [stats, setStats] = useState({}); const [flows, setFlows] = useState([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(""); const [now, setNow] = useState(Date.now()); const [confirmClear, setConfirmClear] = useState(false);
  const refresh = useCallback(async () => { const results = await Promise.allSettled([getCaptureStatus(), getLivePredictions(80), getStats()]); if (results[0].status === "fulfilled") setStatus(results[0].value.data || {}); if (results[1].status === "fulfilled") setFlows(results[1].value.data || []); if (results[2].status === "fulfilled") setStats(results[2].value.data || {}); setError(results.every((item) => item.status === "rejected") ? "The capture service is unavailable because the backend is offline." : ""); }, []);
  useEffect(() => { refresh(); const poll = setInterval(refresh, 2500); const clock = setInterval(() => setNow(Date.now()), 1000); return () => { clearInterval(poll); clearInterval(clock); }; }, [refresh]);
  const action = async (key, fn, message) => { setBusy(key); try { const result = await fn(); push(typeof message === "function" ? message(result) : message); await refresh(); } catch (err) { push(err.response?.data?.detail || err.message || "Capture action failed.", "error"); } finally { setBusy(""); } };
  const duration = useMemo(() => { if (!status.is_running || !status.started_at) return "00:00:00"; const start = new Date(status.started_at.replace(" ", "T")).getTime(); const seconds = Math.max(0, Math.floor((now - start) / 1000)); return [Math.floor(seconds / 3600), Math.floor((seconds % 3600) / 60), seconds % 60].map((value) => String(value).padStart(2, "0")).join(":"); }, [status, now]);
  const timeline = [...flows].reverse().slice(-24).map((row, index) => ({ point: index + 1, packets: row.packets, confidence: Math.round((row.confidence || 0) * 100) }));
  const captureAvailable = status.capture_enabled === true;
  const demoMode = status.demo_mode !== false;
  return <div className="page-stack"><PageHeader eyebrow="Network sensor" title="Live packet capture" description={captureAvailable ? "Monitor packet activity, build bidirectional flows, and classify traffic in real time." : "Cloud demo mode uses safe labeled replay samples; live packet capture is disabled."} aside={<StatusBadge tone={status.is_running ? "success" : "neutral"} dot>{status.is_running ? "Capture running" : captureAvailable ? "Capture stopped" : "Replay demo"}</StatusBadge>} />{error && <ErrorBanner message={error} onRetry={refresh} />}
    <section className="capture-console"><div className="capture-console-head"><div><span className={`capture-pulse large ${status.is_running ? "active" : ""}`}><Radio size={22} /></span><div><strong>{status.is_running ? "Traffic sensor is listening" : captureAvailable ? "Traffic sensor is ready" : "Cloud replay mode is ready"}</strong><p>{status.is_running ? `Started ${status.started_at}` : captureAvailable ? "Choose an interface or use the active default adapter." : "Use Replay BENIGN or Replay DDoS to populate the dashboard safely."}</p></div></div><StatusBadge tone={status.is_running ? "success" : "neutral"}>{status.is_running ? "RUNNING" : captureAvailable ? "STOPPED" : "DEMO"}</StatusBadge></div><div className="capture-controls"><label>Network interface<select value={networkInterface} onChange={(event) => setNetworkInterface(event.target.value)} disabled={status.is_running || !captureAvailable}><option value="">Default active interface</option><option value="Wi-Fi">Wi-Fi</option><option value="Ethernet">Ethernet</option></select><small>{captureAvailable ? "Adapter availability depends on the host and Npcap." : "Network interfaces are unavailable in the hosted demo."}</small></label><div><button className="button button-success" title={!captureAvailable ? "Live packet capture is disabled in the cloud demo" : undefined} disabled={busy || status.is_running || !captureAvailable} onClick={() => action("start", () => startCapture(networkInterface), "Live capture started.")}><Play size={16} />Start capture</button><button className="button button-danger-soft" disabled={busy || !status.is_running || !captureAvailable} onClick={() => action("stop", stopCapture, "Live capture stopped.")}><Square size={15} />Stop</button><button className="button button-ghost" disabled title="Pause is not supported by the current backend"><Pause size={16} />Pause</button><button className="button button-ghost" disabled={busy} onClick={() => action("benign", () => replayBenign(10), (result) => `${result.saved_predictions} BENIGN samples replayed.`)}><RotateCcw size={16} />Replay BENIGN</button><button className="button button-warning" disabled={busy} onClick={() => action("ddos", () => replayDdos(10), (result) => `${result.saved_predictions} DDoS samples replayed.`)}><ShieldAlert size={16} />Replay DDoS</button>{hasPermission("logs:clear") && !demoMode && <button className="button button-danger-soft" onClick={() => setConfirmClear(true)}><Trash2 size={16} />Clear session data</button>}</div></div></section>
    <section className="metrics-grid"><MetricCard icon={Clock3} label="Capture duration" value={duration} detail="Current live session" tone="primary" /><MetricCard icon={Activity} label="Packets processed" value={formatNumber(status.packet_count)} detail="Packets accepted by sensor" tone="info" /><MetricCard icon={Network} label="Flows created" value={formatNumber(status.total_flows)} detail="Bidirectional flows in memory" tone="neutral" /><MetricCard icon={Zap} label="Predictions" value={formatNumber(status.prediction_count)} detail="Saved classification events" tone="primary" /><MetricCard icon={ShieldCheck} label="BENIGN" value={formatNumber(stats.benign_count)} detail="Normal activity stored" tone="success" /><MetricCard icon={ShieldAlert} label="DDoS" value={formatNumber(stats.ddos_count)} detail="Attack activity stored" tone="danger" /><MetricCard icon={Waves} label="Avg. confidence" value={formatConfidence(stats.average_confidence)} detail="Stored prediction mean" tone="warning" /></section>
    <section className="chart-card full-width"><div className="panel-heading"><div><h2>Live traffic timeline</h2><p>Packet volume across the most recent classified flows</p></div><StatusBadge tone={status.is_running ? "success" : "neutral"} dot>{status.is_running ? "Updating every 2.5s" : "Waiting"}</StatusBadge></div>{timeline.length ? <ResponsiveContainer width="100%" height={280}><AreaChart data={timeline}><defs><linearGradient id="packetFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#3182ce" stopOpacity={.3}/><stop offset="95%" stopColor="#3182ce" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#e9e8ef" vertical={false}/><XAxis dataKey="point"/><YAxis/><Tooltip/><Area type="monotone" dataKey="packets" stroke="#3182ce" fill="url(#packetFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer> : <div className="capture-empty"><Ban size={24} /><strong>No classified flow activity yet</strong><p>Start live capture or replay a labeled dataset sample.</p></div>}</section><TrafficTable predictions={flows} />
    <ConfirmDialog open={confirmClear} title="Clear capture session data?" message="The current backend clears all stored predictions and alerts together. Live in-memory flows remain until the API restarts." confirmLabel="Clear stored data" onCancel={() => setConfirmClear(false)} onConfirm={() => { setConfirmClear(false); action("clear", clearDashboardData, "Stored prediction and alert data cleared."); }} />
  </div>;
}
