import { CheckCircle2, Database, FileSearch, Info, RefreshCw, ShieldAlert, Sparkles, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "react-router-dom";
import ErrorBanner from "../../components/common/ErrorBanner";
import PageHeader from "../../components/common/PageHeader";
import StatusBadge from "../../components/common/StatusBadge";
import { FEATURE_NAMES } from "../../app/constants";
import { useToast } from "../../contexts/ToastContext";
import { getRandomDatasetSample, predictManualFlow } from "../../services/api";
import { formatConfidence, formatNumber } from "../../utils/formatters";

const groups = [
  ["Traffic timing", ["Flow Duration"]],
  ["Packet counts", ["Total Fwd Packets", "Total Backward Packets"]],
  ["Traffic volume", ["Total Length of Fwd Packets", "Total Length of Bwd Packets", "Flow Bytes/s", "Flow Packets/s"]],
  ["Packet characteristics", ["Packet Length Mean", "Average Packet Size"]],
  ["TCP flags", ["SYN Flag Count", "ACK Flag Count", "PSH Flag Count"]],
];
const metadata = {
  "Flow Duration": ["Microseconds", "Elapsed lifetime of this flow"], "Total Fwd Packets": ["Packets", "Source-to-destination packet count"], "Total Backward Packets": ["Packets", "Destination-to-source packet count"], "Total Length of Fwd Packets": ["Bytes", "Forward payload volume"], "Total Length of Bwd Packets": ["Bytes", "Backward payload volume"], "Flow Bytes/s": ["Bytes/sec", "Average transfer rate"], "Flow Packets/s": ["Packets/sec", "Average packet rate"], "Packet Length Mean": ["Bytes", "Mean packet length"], "SYN Flag Count": ["Count", "TCP synchronization flags"], "ACK Flag Count": ["Count", "TCP acknowledgement flags"], "PSH Flag Count": ["Count", "TCP push flags"], "Average Packet Size": ["Bytes", "Average flow packet size"],
};
const blank = Object.fromEntries(FEATURE_NAMES.map((name) => [name, ""]));

export default function ManualPredictionPage() {
  const location = useLocation(); const { push } = useToast(); const [features, setFeatures] = useState(blank); const [result, setResult] = useState(null); const [expected, setExpected] = useState(null); const [source, setSource] = useState(""); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [validation, setValidation] = useState({});
  useEffect(() => { const sample = location.state?.sample; if (sample?.features) { setFeatures(Object.fromEntries(FEATURE_NAMES.map((name) => [name, sample.features[name] ?? ""]))); setExpected(sample.label); setSource(sample.source || "Dataset Overview"); setResult(null); } }, [location.state]);
  const setField = (name, value) => { setFeatures((current) => ({ ...current, [name]: value })); if (validation[name]) setValidation((current) => ({ ...current, [name]: "" })); };
  const fillSample = async (type) => { setBusy(type); setError(""); try { const sample = await getRandomDatasetSample(type); setFeatures(Object.fromEntries(FEATURE_NAMES.map((name) => [name, sample.features[name] ?? 0]))); setExpected(sample.sample_label); setSource("CIC-IDS2017 replay endpoint"); setResult(null); push(`${sample.sample_label} dataset sample loaded.`); } catch { setError("The dataset replay service is unavailable. Confirm FastAPI and the dataset files are available."); } finally { setBusy(""); } };
  const predict = async () => { const errors = {}; FEATURE_NAMES.forEach((name) => { if (features[name] === "" || Number.isNaN(Number(features[name])) || Number(features[name]) < 0) errors[name] = "Enter a non-negative numeric value."; }); setValidation(errors); if (Object.keys(errors).length) { setError("Review the highlighted fields before running the prediction."); return; } setBusy("predict"); setError(""); try { setResult(await predictManualFlow(Object.fromEntries(FEATURE_NAMES.map((name) => [name, Number(features[name])])))); } catch { setError("Prediction failed because the backend or model service is unavailable."); } finally { setBusy(""); } };
  const clear = () => { setFeatures(blank); setResult(null); setExpected(null); setSource(""); setValidation({}); setError(""); };
  const strongest = useMemo(() => result ? FEATURE_NAMES.map((name) => [name, Number(features[name])]).sort((a, b) => b[1] - a[1]).slice(0, 3) : [], [result, features]);
  return <div className="page-stack"><PageHeader eyebrow="Explainable inference" title="Manual flow prediction" description="Enter or load the exact 12 features expected by the deployed Random Forest model." actions={<div className="page-actions"><button className="button button-success-soft" disabled={busy} onClick={() => fillSample("BENIGN")}><CheckCircle2 size={16} />Fill BENIGN sample</button><button className="button button-danger-soft" disabled={busy} onClick={() => fillSample("DDOS")}><ShieldAlert size={16} />Fill DDoS sample</button><button className="button button-ghost" disabled={busy} onClick={() => fillSample("MIXED")}><RefreshCw size={16} />Random dataset fill</button></div>} />{error && <ErrorBanner message={error} />}
    <div className="prediction-layout"><section className="prediction-form-card"><div className="form-card-head"><div><span className="icon-box"><FileSearch size={20} /></span><div><h2>Network flow features</h2><p>All values must be zero or greater.</p></div></div>{expected && <StatusBadge tone={expected === "DDoS" ? "danger" : "success"}>Expected: {expected}</StatusBadge>}</div>{source && <div className="sample-source"><Database size={15} /><span>Loaded from {source}</span></div>}<div className="feature-groups">{groups.map(([group, fields]) => <fieldset key={group}><legend>{group}</legend><div className="feature-grid">{fields.map((name) => <label className={validation[name] ? "field-error" : ""} key={name}><span>{name}<button type="button" className="tooltip-trigger" aria-label={`${name}: ${metadata[name][1]}`} title={metadata[name][1]}><Info size={14} /></button></span><div className="unit-input"><input type="number" min="0" step="any" value={features[name]} placeholder={`Enter ${name.toLowerCase()}`} onChange={(event) => setField(name, event.target.value)} aria-invalid={Boolean(validation[name])} /><small>{metadata[name][0]}</small></div>{validation[name] && <em>{validation[name]}</em>}</label>)}</div></fieldset>)}</div><div className="prediction-actions"><button className="button button-primary button-lg" onClick={predict} disabled={busy}>{busy === "predict" ? <><span className="spinner spinner-light" />Analyzing flow…</> : <><Sparkles size={17} />Predict traffic</>}</button><button className="button button-ghost" onClick={clear} disabled={busy}><Trash2 size={16} />Clear form</button></div></section>
      <aside className={`prediction-result-panel ${result ? (result.prediction === "DDoS" ? "attack" : "benign") : "empty"}`}>{result ? <><div className="result-head"><span>{result.prediction === "DDoS" ? <ShieldAlert size={28} /> : <CheckCircle2 size={28} />}</span><div><small>Prediction complete</small><h2>{result.prediction}</h2></div></div><div className="confidence-display"><div><span>Model confidence</span><strong>{formatConfidence(result.confidence)}</strong></div><div className="confidence-track"><i style={{ width: `${(result.confidence || 0) * 100}%` }} /></div></div><div className="result-status"><span>Status</span><strong>{result.status}</strong></div>{expected && <div className="comparison-card"><span>Expected label</span><strong>{expected}</strong><StatusBadge tone={result.prediction === expected ? "success" : "danger"}>{result.prediction === expected ? "Correct match" : "Incorrect match"}</StatusBadge></div>}<div className="reason-card"><span><Sparkles size={16} />Human-readable reason</span><p>{result.reason}</p></div><div className="patterns-card"><strong>Visible feature context</strong>{strongest.map(([name, value]) => <div key={name}><span>{name}</span><b>{formatNumber(value, 2)}</b></div>)}</div><small className="result-disclaimer">The explanation describes visible traffic patterns; it is not a causal model attribution.</small></> : <div className="result-empty"><span><FileSearch size={30} /></span><h2>Your prediction result will appear here</h2><p>Complete all 12 fields or load a labeled dataset sample, then run the classifier.</p><div><span>BENIGN</span><span>DDoS</span><span>Confidence</span><span>Reason</span></div></div>}</aside></div>
  </div>;
}
