import { Award, BarChart3, BrainCircuit, CheckCircle2, ChevronRight, Clock3, Info, ShieldCheck, Target, X } from "lucide-react";
import { useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import MetricCard from "../../components/common/MetricCard";
import PageHeader from "../../components/common/PageHeader";
import StatusBadge from "../../components/common/StatusBadge";
import { modelMetrics } from "../../data/projectData";
import useAuth from "../../hooks/useAuth";
import { formatPercent } from "../../utils/formatters";

export default function ModelsPage() {
  const { hasPermission } = useAuth(); const [selected, setSelected] = useState(null); const [metric, setMetric] = useState("accuracy");
  const deployed = modelMetrics.find((model) => model.deployed); const leader = [...modelMetrics].sort((a, b) => b.accuracy - a.accuracy)[0];
  const chart = modelMetrics.map((model) => ({ name: model.name.replace("Support Vector Machine", "SVM").replace("Logistic Regression", "Logistic"), value: Number((model[metric] * 100).toFixed(2)) }));
  return <div className="page-stack"><PageHeader eyebrow="Detection intelligence" title="Model performance" description="Compare all six classifiers evaluated in the final supervisor-feedback notebook." aside={<StatusBadge tone="info"><Info size={13} />Notebook-backed evaluation</StatusBadge>} />
    <section className="model-hero"><div className="model-hero-badge"><Award size={28} /></div><div><span className="eyebrow">Deployed classifier</span><h2>{deployed.name}</h2><p>{deployed.strength} The deployment artifact is <span className="mono">best_model.pkl</span>.</p><div><StatusBadge tone="success" dot>Deployed</StatusBadge><StatusBadge tone="primary">12 features</StatusBadge><StatusBadge tone="neutral">Binary classification</StatusBadge></div></div><div className="model-hero-score"><small>TEST ACCURACY</small><strong>{formatPercent(deployed.accuracy, 2)}</strong><span>FPR {formatPercent(deployed.fpr, 2)}</span></div></section>
    <section className="metrics-grid"><MetricCard icon={Award} label="Evaluation leader" value={leader.name} detail="Tied test accuracy; notebook selection" tone="primary" /><MetricCard icon={Target} label="Best recall" value={formatPercent(Math.max(...modelMetrics.map((m) => m.recall)), 2)} detail="Naive Bayes evaluation" tone="success" /><MetricCard icon={ShieldCheck} label="Best F1-score" value={formatPercent(Math.max(...modelMetrics.map((m) => m.f1)), 2)} detail="Decision Tree / Random Forest" tone="info" /><MetricCard icon={BrainCircuit} label="Models evaluated" value="6" detail="Classical ML classifiers" tone="neutral" /><MetricCard icon={Clock3} label="Last artifact update" value="May 30, 2026" detail="best_model.pkl workspace timestamp" tone="warning" /></section>
    <section className="chart-card full-width"><div className="panel-heading"><div><h2>Metric comparison</h2><p>Evaluation metrics from the final project notebook</p></div><select value={metric} onChange={(event) => setMetric(event.target.value)}><option value="accuracy">Accuracy</option><option value="precision">Precision</option><option value="recall">Recall</option><option value="f1">F1-score</option><option value="fpr">False positive rate</option></select></div><ResponsiveContainer width="100%" height={330}><BarChart data={chart} margin={{ left: 5, right: 10 }}><CartesianGrid stroke="#e9e8ef" vertical={false}/><XAxis dataKey="name" interval={0} tick={{ fill: "#6d6a7c", fontSize: 11 }} /><YAxis domain={metric === "fpr" ? [0, 60] : [0, 100]} tickFormatter={(value) => `${value}%`} /><Tooltip formatter={(value) => `${value}%`} /><Bar dataKey="value" name={metric.toUpperCase()} fill="#7667f5" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></section>
    <section className="model-grid">{modelMetrics.map((model) => <article className={`model-card ${model.deployed ? "deployed" : ""}`} key={model.name}><div className="model-card-head"><span className="model-icon"><BrainCircuit size={20} /></span><div>{model.deployed && <StatusBadge tone="success" dot>Deployed</StatusBadge>}<StatusBadge tone={model.status === "Active" ? "success" : model.status === "Validated" ? "info" : "neutral"}>{model.status}</StatusBadge></div></div><h3>{model.name}</h3><p className="mono model-file">{model.file}</p><div className="model-score-grid"><div><span>Accuracy</span><strong>{formatPercent(model.accuracy, 2)}</strong></div><div><span>Precision</span><strong>{formatPercent(model.precision, 2)}</strong></div><div><span>Recall</span><strong>{formatPercent(model.recall, 2)}</strong></div><div><span>F1-score</span><strong>{formatPercent(model.f1, 2)}</strong></div></div><p>{model.strength}</p><button className="text-button" onClick={() => setSelected(model)}>View full evaluation <ChevronRight size={15} /></button></article>)}</section>
    <div className="source-note"><Info size={16} /><div><strong>Evaluation source and limitations</strong><p>Metrics are real outputs from <span className="mono">(Final_update_supervisor_feedback)Network_Traffic_Anomaly_Detection.ipynb</span>. Training and testing times were not recorded, so the interface does not invent them. Results describe this dataset split, not future production traffic.</p></div></div>
    {selected && <div className="modal-backdrop" onMouseDown={() => setSelected(null)}><section className="drawer model-drawer" role="dialog" aria-modal="true" aria-labelledby="model-title" onMouseDown={(event) => event.stopPropagation()}><button className="dialog-close icon-button" onClick={() => setSelected(null)} aria-label="Close details"><X size={19} /></button><span className="eyebrow">Model evaluation</span><h2 id="model-title">{selected.name}</h2><p className="mono">{selected.file}</p><div className="model-detail-status"><StatusBadge tone={selected.deployed ? "success" : "neutral"}>{selected.deployed ? "Currently deployed" : "Available artifact"}</StatusBadge><StatusBadge tone="info">{selected.status}</StatusBadge></div><div className="detail-metrics">{[["Accuracy", selected.accuracy], ["Precision", selected.precision], ["Recall / Detection rate", selected.recall], ["F1-score", selected.f1], ["False positive rate", selected.fpr], ["False negative rate", 1 - selected.recall], ["ROC-AUC", selected.auc]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{formatPercent(value, 2)}</strong></div>)}</div><div className="detail-block"><h3>Strength</h3><p>{selected.strength}</p></div><div className="detail-block"><h3>Limitation</h3><p>{selected.limitation}</p></div><div className="detail-block"><h3>Training and testing time</h3><p>Not recorded in the available final notebook output.</p></div>{hasPermission("models:manage") && <button className="button button-primary" disabled title="Model switching needs a protected backend endpoint"><CheckCircle2 size={16} />Deploy model — backend not connected</button>}</section></div>}
  </div>;
}
