import { Clock3, KeyRound, LogOut, Mail, MonitorSmartphone, ShieldCheck, UserRound } from "lucide-react";
import { useState } from "react";
import MetricCard from "../../components/common/MetricCard";
import PageHeader from "../../components/common/PageHeader";
import StatusBadge from "../../components/common/StatusBadge";
import { ROLE_LABELS } from "../../app/constants";
import { useToast } from "../../contexts/ToastContext";
import useAuth from "../../hooks/useAuth";

export default function ProfilePage() {
  const { user, sessionStartedAt, logout } = useAuth(); const { push } = useToast(); const [passwords, setPasswords] = useState({ current: "", next: "", confirm: "" });
  const changePassword = (event) => { event.preventDefault(); if (!passwords.current || passwords.next.length < 8 || passwords.next !== passwords.confirm) { push("Check the current password and ensure the new passwords match.", "error"); return; } push("Password changes require the future FastAPI authentication endpoint.", "error"); };
  return <div className="page-stack"><PageHeader eyebrow="Account security" title="Profile & session" description="Review your identity, access role, and current authentication session."/><section className="profile-hero"><span className="profile-avatar-large">{user?.name?.split(" ").map((part) => part[0]).slice(0,2).join("")}</span><div><h2>{user?.name}</h2><p>{user?.email}</p><div><StatusBadge tone={user?.role === "ADMIN" ? "primary" : "info"}>{ROLE_LABELS[user?.role]}</StatusBadge><StatusBadge tone="success" dot>{user?.status || "Active"}</StatusBadge></div></div><button className="button button-ghost" onClick={logout}><LogOut size={16}/>Sign out</button></section><section className="metrics-grid"><MetricCard icon={UserRound} label="Account status" value={user?.status || "Active"} detail="Mock authentication directory" tone="success"/><MetricCard icon={ShieldCheck} label="Access role" value={ROLE_LABELS[user?.role]} detail="Applied to routes and actions" tone="primary"/><MetricCard icon={Clock3} label="Session started" value={sessionStartedAt ? new Date(sessionStartedAt).toLocaleTimeString() : "—"} detail={sessionStartedAt ? new Date(sessionStartedAt).toLocaleDateString() : "Current session"} tone="info"/><MetricCard icon={MonitorSmartphone} label="Session device" value="This browser" detail="Local development session" tone="neutral"/></section><div className="profile-grid"><section className="data-panel"><div className="panel-heading"><div><h2>Account information</h2><p>Identity supplied by the active authentication service</p></div></div><div className="profile-details"><div><UserRound size={17}/><span>Name</span><strong>{user?.name}</strong></div><div><Mail size={17}/><span>Email</span><strong>{user?.email}</strong></div><div><ShieldCheck size={17}/><span>Role</span><strong>{ROLE_LABELS[user?.role]}</strong></div><div><Clock3 size={17}/><span>Last login</span><strong>{sessionStartedAt ? new Date(sessionStartedAt).toLocaleString() : "Current session"}</strong></div></div></section><section className="data-panel"><div className="panel-heading"><div><h2>Change password</h2><p>Prepared for future JWT account management</p></div><StatusBadge tone="warning">Backend required</StatusBadge></div><form className="password-form" onSubmit={changePassword}><label>Current password<input type="password" value={passwords.current} onChange={(event) => setPasswords({...passwords,current:event.target.value})}/></label><label>New password<input type="password" minLength="8" value={passwords.next} onChange={(event) => setPasswords({...passwords,next:event.target.value})}/></label><label>Confirm new password<input type="password" value={passwords.confirm} onChange={(event) => setPasswords({...passwords,confirm:event.target.value})}/></label><button className="button button-primary"><KeyRound size={16}/>Update password</button></form></section></div></div>;
}
