import { ChevronLeft, ChevronRight, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { formatConfidence, formatDateTime } from "../utils/formatters";
import EmptyState from "./common/EmptyState";
import StatusBadge from "./common/StatusBadge";

export default function TrafficTable({ predictions = [], loading = false, compact = false }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ALL"); const [page, setPage] = useState(1);
  const pageSize = compact ? 6 : 10;
  const filtered = useMemo(() => predictions.filter((row) => (filter === "ALL" || row.prediction === filter) && [row.src_ip, row.dst_ip, row.protocol, row.prediction].some((value) => String(value || "").toLowerCase().includes(query.toLowerCase()))), [predictions, query, filter]);
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const safePage = Math.min(page, pages); const rows = filtered.slice((safePage - 1) * pageSize, safePage * pageSize);
  return <section className="data-panel"><div className="panel-heading"><div><h2>Live predictions</h2><p>Most recent classified network flows</p></div><div className="table-tools"><label className="search-field"><Search size={16} /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Search traffic" aria-label="Search traffic" /></label><select value={filter} onChange={(event) => { setFilter(event.target.value); setPage(1); }} aria-label="Filter prediction"><option value="ALL">All traffic</option><option value="BENIGN">BENIGN</option><option value="DDoS">DDoS</option></select></div></div>{loading ? <div className="table-skeleton"><i /><i /><i /><i /></div> : rows.length ? <><div className="table-scroll"><table><thead><tr><th>ID</th><th>Source IP</th><th>Destination IP</th><th>Protocol</th><th>Packets</th><th>Prediction</th><th>Confidence</th><th>Time</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td className="mono muted">#{item.id}</td><td className="mono">{item.src_ip}</td><td className="mono">{item.dst_ip}</td><td>{item.protocol}</td><td>{item.packets}</td><td><StatusBadge tone={item.prediction === "DDoS" ? "danger" : "success"} dot>{item.prediction}</StatusBadge></td><td><div className="confidence-cell"><span><i style={{ width: `${Math.round((item.confidence || 0) * 100)}%` }} /></span><strong>{formatConfidence(item.confidence)}</strong></div></td><td className="muted">{formatDateTime(item.created_at || item.timestamp)}</td></tr>)}</tbody></table></div><div className="table-pagination"><span>Showing {(safePage - 1) * pageSize + 1}–{Math.min(safePage * pageSize, filtered.length)} of {filtered.length}</span><div><button className="icon-button" disabled={safePage === 1} onClick={() => setPage((value) => value - 1)} aria-label="Previous page"><ChevronLeft size={16} /></button><span>Page {safePage} of {pages}</span><button className="icon-button" disabled={safePage === pages} onClick={() => setPage((value) => value + 1)} aria-label="Next page"><ChevronRight size={16} /></button></div></div></> : <EmptyState title="No predictions found" message={predictions.length ? "Try changing your search or filter." : "Start capture or replay traffic to populate this feed."} />}</section>;
}
