import { ArrowRight, CheckCircle2, ChevronRight, Network, Shield, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { capabilityCards, landingProcess } from "../../data/projectData";

export default function LandingPage() {
  const traffic = [{ name: "BENIGN", value: 627636 }, { name: "DDoS", value: 128027 }];
  return <div className="landing-page">
    <nav className="landing-nav"><Link className="landing-brand" to="/"><span><Shield size={21} /></span><div><strong>NetShield IDS</strong><small>Threat Detection Platform</small></div></Link><div><a href="#capabilities">Capabilities</a><a href="#architecture">Architecture</a><Link className="button button-ghost" to="/login">Sign in</Link><Link className="button button-primary" to="/login">Launch NetShield <ArrowRight size={16} /></Link></div></nav>
    <main>
      <section className="hero-section">
        <div className="hero-copy"><span className="hero-kicker"><Sparkles size={15} />Machine learning-powered network defense</span><h1>Detect network threats <em>before they disrupt</em> your systems.</h1><p>NetShield IDS monitors network traffic, detects DDoS attacks, explains predictions, and delivers real-time security alerts from one focused workspace.</p><div className="hero-actions"><Link className="button button-primary button-lg" to="/login">Launch NetShield <ArrowRight size={17} /></Link><a className="button button-ghost button-lg" href="#capabilities">View system capabilities</a></div><div className="hero-trust"><span><CheckCircle2 size={16} />12 selected flow features</span><span><CheckCircle2 size={16} />Explainable results</span><span><CheckCircle2 size={16} />Role-based access</span></div></div>
        <div className="hero-visual" aria-label="NetShield security dashboard preview">
          <div className="preview-chrome"><span /><span /><span /><small>Security Operations / Live</small></div>
          <div className="preview-body"><aside><Shield size={19} /><i /><i /><i /><i /></aside><div className="preview-main"><div className="preview-head"><div><small>NETWORK POSTURE</small><strong>Threat activity is contained</strong></div><span><i />Live capture</span></div><div className="preview-metrics"><article><small>Total flows</small><strong>755,663</strong><em>Analyzed</em></article><article><small>DDoS traffic</small><strong>128,027</strong><em>Detected</em></article><article><small>Model confidence</small><strong>99.9%</strong><em>Random Forest</em></article></div><div className="preview-grid"><div className="preview-chart"><small>Traffic classification</small><ResponsiveContainer width="100%" height={150}><PieChart><Pie data={traffic} dataKey="value" innerRadius={44} outerRadius={64} paddingAngle={4}>{traffic.map((_, index) => <Cell key={index} fill={index ? "#ef5b68" : "#22c997"} />)}</Pie></PieChart></ResponsiveContainer></div><div className="preview-bars"><small>Detection activity</small><ResponsiveContainer width="100%" height={150}><BarChart data={[{ v: 22 }, { v: 36 }, { v: 28 }, { v: 52 }, { v: 40 }, { v: 68 }, { v: 49 }]}><Bar dataKey="v" fill="#7667f5" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></div></div></div>
          <div className="floating-alert"><span><Shield size={17} /></span><div><small>High-confidence detection</small><strong>DDoS flow contained</strong></div></div>
        </div>
      </section>
      <section className="landing-section" id="capabilities"><div className="section-heading"><span className="eyebrow">Platform capabilities</span><h2>Built for fast, explainable detection</h2><p>Move from packet activity to an actionable security decision without losing the evidence behind it.</p></div><div className="capability-grid">{capabilityCards.map(([Icon, title, copy]) => <article key={title}><span><Icon size={20} /></span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
      <section className="landing-section process-section"><div className="section-heading left"><span className="eyebrow">Detection pipeline</span><h2>From raw traffic to a clear decision</h2></div><div className="process-track">{landingProcess.map((step, index) => <div key={step}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong>{index < landingProcess.length - 1 && <ChevronRight size={18} />}</div>)}</div></section>
      <section className="landing-section performance-section"><div className="performance-copy"><span className="eyebrow">Evaluation snapshot</span><h2>High detection quality, grounded in CIC-IDS2017</h2><p>The deployed Random Forest achieved a 99.90% test accuracy and 0.02% false-positive rate in the final project notebook evaluation.</p><div><article><strong>99.90%</strong><span>Test accuracy</span></article><article><strong>99.83%</strong><span>DDoS recall</span></article><article><strong>0.02%</strong><span>False positive rate</span></article></div><small>Source: final supervisor-feedback notebook. Results reflect the evaluated dataset and are not production guarantees.</small></div><div className="performance-card"><ResponsiveContainer width="100%" height={260}><BarChart layout="vertical" data={[{ name: "Decision Tree", score: 99.90 }, { name: "Random Forest", score: 99.90 }, { name: "KNN", score: 99.89 }, { name: "SVM", score: 87.09 }, { name: "Logistic", score: 75.35 }, { name: "Naive Bayes", score: 73.51 }]} margin={{ left: 8, right: 18 }}><XAxis type="number" domain={[0, 100]} hide /><YAxis type="category" dataKey="name" width={92} axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#666375" }} /><Tooltip formatter={(value) => `${value}%`} /><Bar dataKey="score" fill="#7667f5" radius={[0, 5, 5, 0]} barSize={18} /></BarChart></ResponsiveContainer><div className="performance-legend"><span>Evaluated test accuracy</span><strong>Six models compared</strong></div></div></section>
      <section className="landing-section architecture-section" id="architecture"><div className="section-heading"><span className="eyebrow">System architecture</span><h2>A complete detection loop</h2></div><div className="architecture-flow"><div><Network size={24} /><strong>Network packets</strong><span>Scapy capture</span></div><ChevronRight /><div><BarChartIcon /><strong>Flow intelligence</strong><span>12 selected features</span></div><ChevronRight /><div><Shield size={24} /><strong>ML decision</strong><span>BENIGN or DDoS</span></div><ChevronRight /><div><Sparkles size={24} /><strong>Response</strong><span>Explain, alert, log</span></div></div><div className="stack-row"><span>React</span><span>FastAPI</span><span>scikit-learn</span><span>SQLite</span><span>Scapy</span><span>CIC-IDS2017</span></div></section>
      <section className="landing-cta"><div><span className="eyebrow">Ready to monitor</span><h2>Turn network activity into security intelligence.</h2></div><Link className="button button-light button-lg" to="/login">Open secure workspace <ArrowRight size={17} /></Link></section>
    </main>
    <footer className="landing-footer"><div><div className="landing-brand"><span><Shield size={20} /></span><div><strong>NetShield IDS</strong><small>Machine Learning-Based Network Traffic Anomaly Detection</small></div></div><p>Final-year cybersecurity project • Academic Year 2025/2026</p></div><div><strong>Technology</strong><span>React · FastAPI · Random Forest · CIC-IDS2017</span></div><div><strong>Documentation</strong><span>API documentation available at /docs</span></div></footer>
  </div>;
}

function BarChartIcon() { return <Network size={24} />; }
