import { ArrowLeft, BellRing, CheckCircle2, Eye, EyeOff, LockKeyhole, Radio, Shield, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import useAuth from "../../hooks/useAuth";

export default function LoginPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [remember, setRemember] = useState(false); const [show, setShow] = useState(false);
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const submit = async (event) => { event.preventDefault(); setError(""); if (!email || !password) { setError("Enter both your email and password."); return; } setLoading(true); try { await login(email, password, remember); navigate(location.state?.from || "/dashboard", { replace: true }); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const trust = [[ShieldCheck, "Role-based access"], [LockKeyhole, "Secure monitoring"], [Radio, "Intelligent detection"], [BellRing, "Real-time alerts"]];
  return <main className="login-page"><section className="login-brand-panel"><Link to="/" className="login-back"><ArrowLeft size={16} />Back to landing</Link><div className="login-brand-copy"><span className="login-logo"><Shield size={28} /></span><span className="eyebrow">NetShield IDS</span><h1>Your network.<br />Under intelligent watch.</h1><p>Operate live detection, investigate explainable alerts, and protect administrative controls from one secure workspace.</p><div className="trust-grid">{trust.map(([Icon, label]) => <div key={label}><Icon size={19} /><span>{label}</span></div>)}</div><div className="login-activity-preview"><div><span><Radio size={16} /></span><div><small>Detection engine</small><strong>Online and ready</strong></div><b>LIVE</b></div><div><span className="traffic-dot benign" /><strong>BENIGN traffic</strong><small>99.8% confidence</small></div><div><span className="traffic-dot attack" /><strong>DDoS detection</strong><small>Alert workflow armed</small></div></div></div><p className="login-copyright">Academic security platform • NetShield IDS v2.0</p></section><section className="login-form-panel"><form className="login-card" onSubmit={submit} noValidate><div className="login-card-head"><span className="eyebrow">Secure access</span><h2>Welcome back</h2><p>Sign in to your NetShield workspace.</p></div>{error && <div className="login-error" role="alert">{error}</div>}<label>Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="name@netshield.local" autoComplete="email" /></label><label>Password<div className="password-field"><input type={show ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" autoComplete="current-password" /><button type="button" onClick={() => setShow((value) => !value)} aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label><div className="remember-row"><label><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} />Remember this device</label><span>Protected session</span></div><button className="button button-primary button-lg login-submit" disabled={loading}>{loading ? <><span className="spinner spinner-light" />Authenticating…</> : <>Sign in securely <CheckCircle2 size={17} /></>}</button><p className="login-help">Development authentication is active. Use credentials provided in the project handoff.</p></form></section></main>;
}
